# Generated by Django 5.0 on 2026-05-15 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='plataforma',
        ),
        migrations.AddField(
            model_name='perfil',
            name='plataformas',
            field=models.ManyToManyField(blank=True, to='inventario.plataforma'),
        ),
    ]
