# Generated by Django 5.0 on 2026-05-17 00:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_plataforma_remove_perfil_plataforma_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='SKU')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('marca', models.CharField(blank=True, max_length=100, null=True, verbose_name='Marca')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título / Descripción')),
                ('codigo_ean', models.CharField(blank=True, max_length=100, null=True, verbose_name='Código EAN')),
                ('ubicacion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ubicación Base')),
                ('costo_dolares', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Costo Unit. ($)')),
                ('costo_soles', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Costo Cero (S/.)')),
                ('precio_mercado_libre', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('precio_falabella', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('precio_web', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('precio_creditienda', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoPercheron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('IN', 'Ingreso (+)'), ('OUT', 'Salida (-)')], max_length=10)),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('fecha', models.DateField(verbose_name='Fecha de Operación')),
                ('serie', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nro. Serie')),
                ('costo_transaccion', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo Unit. (S/.) en este mov.')),
                ('proveedor_motivo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Proveedor / Motivo (Ingreso)')),
                ('documento_salida', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nro. Orden / Boleta (Salida)')),
                ('canal_venta', models.CharField(blank=True, max_length=100, null=True, verbose_name='Canal de Venta (Salida)')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_percheron', to='inventario.producto')),
            ],
            options={
                'ordering': ['-fecha', '-creado_en'],
            },
        ),
    ]
