# Generated by Django 5.0 on 2026-05-17 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_producto_movimientopercheron'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='precio_creditienda',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precio_falabella',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precio_mercado_libre',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precio_web',
        ),
        migrations.AddField(
            model_name='producto',
            name='activo_creditienda',
            field=models.BooleanField(default=False, verbose_name='Creditienda'),
        ),
        migrations.AddField(
            model_name='producto',
            name='activo_falabella',
            field=models.BooleanField(default=False, verbose_name='Falabella'),
        ),
        migrations.AddField(
            model_name='producto',
            name='activo_intercorp',
            field=models.BooleanField(default=False, verbose_name='Intercorp'),
        ),
        migrations.AddField(
            model_name='producto',
            name='activo_ml',
            field=models.BooleanField(default=False, verbose_name='Mercado Libre'),
        ),
        migrations.AddField(
            model_name='producto',
            name='activo_ml_jr',
            field=models.BooleanField(default=False, verbose_name='Mercado Libre Junior'),
        ),
        migrations.AddField(
            model_name='producto',
            name='activo_web',
            field=models.BooleanField(default=False, verbose_name='Página Web'),
        ),
    ]
