# Generated by Django 5.0 on 2026-05-21 04:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_remove_producto_precio_creditienda_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulacionMercadoLibre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('item_type', models.CharField(blank=True, max_length=20, null=True)),
                ('link', models.URLField(blank=True, max_length=500, null=True)),
                ('estado_publicacion', models.CharField(blank=True, max_length=20, null=True)),
                ('cod_publicacion', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_publicacion', models.CharField(blank=True, max_length=30, null=True)),
                ('cod_producto', models.CharField(blank=True, max_length=50, null=True)),
                ('categoria', models.CharField(blank=True, max_length=150, null=True)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('producto', models.CharField(blank=True, max_length=255, null=True)),
                ('precio_tachado', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('porc_descuento', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('precio_venta', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('costo_envio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('porc_comision', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('comision_soles', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('pago_neto', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('costo_producto', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ganancia', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('rentabilidad_porc', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('mpe', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulaciones_mercadolibre', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Simulación Mercado Libre',
                'verbose_name_plural': 'Simulaciones Mercado Libre',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
