# Generated by Django 5.0 on 2026-05-23 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_simulacionmercadolibre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_categoria', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='ReferenciaComision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_categoria', models.CharField(blank=True, max_length=200, null=True)),
                ('categoria', models.CharField(max_length=200, unique=True)),
                ('comision', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
        ),
    ]
