# Generated by Django 5.0 on 2026-05-23 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_comision_referenciacomision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referenciacomision',
            name='categoria',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='referenciacomision',
            name='sub_categoria',
            field=models.CharField(default='N/A', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
