# Generated by Django 5.0 on 2026-05-23 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_alter_referenciacomision_categoria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenciaCosto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, unique=True)),
                ('producto', models.CharField(blank=True, max_length=255, null=True)),
                ('costo_cero', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('costo_u_dolares', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('costo_u_soles', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
    ]
