# Generated by Django 5.0 on 2026-05-26 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_referenciacosto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comision',
            name='porcentaje',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='referenciacomision',
            name='comision',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='simulacionmercadolibre',
            name='porc_comision',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='simulacionmercadolibre',
            name='porc_descuento',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='simulacionmercadolibre',
            name='rentabilidad_porc',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
