# Generated by Django 5.0 on 2026-06-01 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_alter_comision_porcentaje_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteMercadoLibre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('mes_anio', models.CharField(max_length=50)),
                ('nro_orden', models.CharField(max_length=100, unique=True)),
                ('comprobante', models.CharField(max_length=100)),
                ('tipo_venta', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
                ('sku_almacen', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('producto', models.CharField(max_length=255)),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_venta', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cargo_venta', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('urbano', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('flex', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_pagado', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('costo_producto', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('und', models.IntegerField(default=0)),
                ('costo_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('costo_entrega_flex', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ganancia', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('rentabilidad', models.CharField(max_length=20)),
                ('distrito', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('repartidor', models.CharField(max_length=100)),
                ('celular', models.CharField(max_length=20)),
                ('mensaje', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
