# Generated by Django 5.0 on 2026-06-02 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_reportemercadolibre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportemercadolibre',
            name='categoria',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='reportemercadolibre',
            name='celular',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='reportemercadolibre',
            name='comprobante',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='reportemercadolibre',
            name='direccion',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='reportemercadolibre',
            name='distrito',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='reportemercadolibre',
            name='marca',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='reportemercadolibre',
            name='mensaje',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='reportemercadolibre',
            name='mes_anio',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reportemercadolibre',
            name='modelo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='reportemercadolibre',
            name='nro_orden',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='reportemercadolibre',
            name='producto',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='reportemercadolibre',
            name='rentabilidad',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='reportemercadolibre',
            name='repartidor',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='reportemercadolibre',
            name='sku_almacen',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='reportemercadolibre',
            name='tipo_venta',
            field=models.CharField(max_length=255),
        ),
    ]
