# Generated by Django 5.0 on 2026-06-04 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_alter_reportemercadolibre_categoria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngresoPercheron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=150, unique=True, verbose_name='SKU Autogenerado')),
                ('modelo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Modelo')),
                ('titulo', models.CharField(blank=True, max_length=500, null=True, verbose_name='Título')),
                ('fecha_ingreso', models.DateField(blank=True, null=True, verbose_name='Fecha de Ingreso')),
                ('codigo_ean', models.CharField(blank=True, max_length=150, null=True, verbose_name='Código EAN')),
                ('serie_nro', models.CharField(max_length=200, unique=True, verbose_name='Serie / N°')),
                ('costo_unitario', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Costo Unt.')),
                ('cantidad', models.IntegerField(default=1, verbose_name='Ing. x 1 und')),
                ('proveedor_motivo', models.CharField(blank=True, max_length=300, null=True, verbose_name='Proveedor / Motivo')),
                ('creado_por', models.CharField(blank=True, max_length=150, null=True, verbose_name='By:')),
            ],
        ),
    ]
