# Generated by Django 5.0 on 2026-06-04 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0012_ingresopercheron'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingresopercheron',
            name='serie_nro',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Serie / N°'),
        ),
        migrations.AlterField(
            model_name='ingresopercheron',
            name='sku',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='SKU Autogenerado'),
        ),
    ]
