# Generated by Django 5.0 on 2026-06-05 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0013_alter_ingresopercheron_serie_nro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Categoría'),
        ),
    ]
