# Generated by Django 5.0 on 2026-06-07 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0014_producto_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalidaMercadoLibre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('titulo', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_salida', models.DateField(blank=True, null=True)),
                ('serie', models.CharField(blank=True, max_length=100, null=True)),
                ('costo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('descuento', models.IntegerField(default=1)),
                ('nro_venta', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_venta', models.CharField(blank=True, max_length=50, null=True)),
                ('creado_por', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]