# Generated by Django 5.0 on 2026-06-13 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0015_salidamercadolibre_producto_stock_actual'),
    ]

    operations = [
        # BLOQUE COMENTADO: Lo ocultamos porque la columna stock_actual ya existe en Render
        # y no queremos que Django intente crearla de nuevo y nos tire error.
        # migrations.AddField(
        #     model_name='producto',
        #     name='stock_actual',
        #     field=models.IntegerField(default=0, verbose_name='Stock Actual'),
        # ),
        
        # BLOQUE ACTIVO: Este sí lo dejamos para que convierta tu columna MPE a texto.
        migrations.AlterField(
            model_name='simulacionmercadolibre',
            name='mpe',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]