# Generated by Django 5.0 on 2026-06-19 04:39

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0016_producto_stock_actual_and_more'),
    ]

    operations = [
        # comentamos esta parte porque la columna stock_actual ya existe en neon
        # migrations.AddField(
        #     model_name='producto',
        #     name='stock_actual',
        #     field=models.IntegerField(default=0, verbose_name='Stock Actual'),
        # ),
    ]