# Generated by Django 5.0 on 2026-06-20 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0017_producto_stock_actual'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteMercadoLibreJunior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_orden', models.CharField(max_length=255, unique=True)),
                ('fecha', models.DateField()),
                ('mes_anio', models.CharField(blank=True, max_length=100, null=True)),
                ('nro_operacion', models.CharField(blank=True, max_length=255, null=True)),
                ('estado_pago', models.CharField(blank=True, max_length=100, null=True)),
                ('comprobante', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_venta', models.CharField(blank=True, max_length=255, null=True)),
                ('marca', models.CharField(blank=True, max_length=255, null=True)),
                ('categoria', models.CharField(blank=True, max_length=255, null=True)),
                ('sku_almacen', models.CharField(blank=True, max_length=255, null=True)),
                ('modelo', models.CharField(blank=True, max_length=255, null=True)),
                ('producto', models.CharField(blank=True, max_length=255, null=True)),
                ('cantidad', models.FloatField(default=0)),
                ('precio', models.FloatField(default=0)),
                ('total_venta', models.FloatField(default=0)),
                ('cargo_venta', models.FloatField(default=0)),
                ('urbano', models.FloatField(default=0)),
                ('flex', models.FloatField(default=0)),
                ('total_pagado', models.FloatField(default=0)),
                ('costo_producto', models.FloatField(default=0)),
                ('und', models.IntegerField(default=0)),
                ('costo_total', models.FloatField(default=0)),
                ('costo_entrega_flex', models.FloatField(default=0)),
                ('ganancia', models.FloatField(default=0)),
                ('rentabilidad', models.CharField(blank=True, max_length=100, null=True)),
                ('distrito', models.CharField(blank=True, max_length=255, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('repartidor', models.CharField(blank=True, max_length=255, null=True)),
                ('celular', models.CharField(blank=True, max_length=255, null=True)),
                ('mensaje', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        
        # Bloque comentado para evitar el ProgrammingError (stock_actual ya existe en BD)
        # migrations.AddField(
        #     model_name='producto',
        #     name='stock_actual',
        #     field=models.IntegerField(default=0, verbose_name='Stock Actual'),
        # ),
    ]