# Generated by Django 5.0 on 2026-06-20 21:42

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0019_producto_stock_actual_and_more'),
    ]

    operations = [
        # === BLINDAJE APLICADO: CREA LA TABLA SOLO SI NO EXISTE EN RENDER ===
        migrations.RunSQL(
            sql="""
            CREATE TABLE IF NOT EXISTS "inventario_salidamercadolibrejunior" (
                "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                "sku" varchar(100) NULL,
                "modelo" varchar(100) NULL,
                "titulo" varchar(255) NULL,
                "fecha_salida" date NULL,
                "serie" varchar(100) NULL,
                "costo" numeric(10, 2) NOT NULL,
                "descuento" integer NOT NULL,
                "nro_venta" varchar(100) NULL,
                "tipo_venta" varchar(50) NULL,
                "creado_por" varchar(50) NULL
            );
            """,
            state_operations=[
                migrations.CreateModel(
                    name='SalidaMercadoLibreJunior',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('sku', models.CharField(blank=True, max_length=100, null=True)),
                        ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                        ('titulo', models.CharField(blank=True, max_length=255, null=True)),
                        ('fecha_salida', models.DateField(blank=True, null=True)),
                        ('serie', models.CharField(blank=True, max_length=100, null=True)),
                        ('costo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                        ('descuento', models.IntegerField(default=1)),
                        ('nro_venta', models.CharField(blank=True, max_length=100, null=True)),
                        ('tipo_venta', models.CharField(blank=True, max_length=50, null=True)),
                        ('creado_por', models.CharField(blank=True, max_length=50, null=True)),
                    ],
                ),
            ]
        ),
    ]