# Generated by Django 5.0 on 2026-06-21 04:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0021_salidacreditienda_salidafalabella_salidaintercorp_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteCreditienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_venta', models.DateField(blank=True, null=True)),
                ('fecha_despacho', models.DateField(blank=True, null=True)),
                ('mes_ano', models.CharField(blank=True, max_length=50, null=True)),
                ('estado_pedido', models.CharField(blank=True, max_length=100, null=True)),
                ('nro_orden', models.CharField(blank=True, max_length=100, null=True)),
                ('cliente', models.CharField(blank=True, max_length=255, null=True)),
                ('boleta', models.CharField(blank=True, max_length=100, null=True)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('categoria', models.CharField(blank=True, max_length=150, null=True)),
                ('sku_almacen', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo', models.CharField(blank=True, max_length=100, null=True)),
                ('producto', models.CharField(blank=True, max_length=255, null=True)),
                ('cantidad', models.IntegerField(default=1)),
                ('precio_venta', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_venta', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('porc_comision', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('comision_soles', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('pago_plataforma', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('envio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('costo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ganancia', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('rentabilidad', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('check_pago', models.BooleanField(default=False)),
                ('venta_pagada', models.CharField(blank=True, max_length=50, null=True)),
                ('se_adjunto', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_validacion', models.DateField(blank=True, null=True)),
                ('nro_operacion', models.CharField(blank=True, max_length=100, null=True)),
                ('nro_telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_creditienda', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte Creditienda',
                'verbose_name_plural': 'Reportes Creditienda',
                'ordering': ['-fecha_venta'],
            },
        ),
    ]
