# Generated by Django 5.0 on 2026-06-21 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0022_reportecreditienda'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteFalabella',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('mes_ano', models.CharField(blank=True, max_length=50, null=True)),
                ('nro_orden', models.CharField(blank=True, max_length=100, null=True)),
                ('boleta_factura', models.CharField(blank=True, max_length=100, null=True)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('categoria', models.CharField(blank=True, max_length=150, null=True)),
                ('sku_almacen', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo', models.CharField(blank=True, max_length=100, null=True)),
                ('producto', models.CharField(blank=True, max_length=255, null=True)),
                ('cant', models.IntegerField(default=1)),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('v_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('comision_porc', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('comision_soles', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('costo_envio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_pagado', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('costo_x_prod', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cantidad', models.IntegerField(default=1)),
                ('c_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ganancia', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('rtbld', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('nro_operacion', models.CharField(blank=True, max_length=100, null=True)),
                ('estado_pago', models.CharField(blank=True, max_length=100, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_falabella', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte Falabella',
                'verbose_name_plural': 'Reportes Falabella',
                'ordering': ['-fecha'],
            },
        ),
    ]
