# Generated by Django 5.0 on 2026-06-21 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0024_directorioproducto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteIntercorp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('sitio', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('mes_ano', models.CharField(blank=True, max_length=20, null=True)),
                ('id_orden', models.CharField(blank=True, max_length=100, null=True)),
                ('comprobante_venta', models.CharField(blank=True, max_length=100, null=True)),
                ('sku_almacen', models.CharField(blank=True, max_length=100, null=True)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo', models.CharField(blank=True, max_length=100, null=True)),
                ('producto', models.CharField(blank=True, max_length=255, null=True)),
                ('und', models.IntegerField(blank=True, default=1, null=True)),
                ('p_venta', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('costo_envio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('monto_total_facturable', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('impuesto', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cobro_logistico', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('costo_prod', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ganancia', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('monto_a_pagar', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('id_liquidacion', models.CharField(blank=True, max_length=100, null=True)),
                ('estado_pago', models.CharField(blank=True, max_length=100, null=True)),
                ('id_pago', models.CharField(blank=True, max_length=100, null=True)),
                ('validacion', models.CharField(blank=True, max_length=100, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reportes_intercorp', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte Intercorp',
                'verbose_name_plural': 'Reportes Intercorp',
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
