# Generated by Django 5.0 on 2026-06-22 03:53

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0026_comisionintercorp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salidaintercorp',
            options={'verbose_name': 'Salida Intercorp'},
        ),
        migrations.RenameField(
            model_name='salidaintercorp',
            old_name='costo',
            new_name='costo_unt',
        ),
        migrations.RenameField(
            model_name='salidaintercorp',
            old_name='descuento',
            new_name='desc_und',
        ),
        migrations.RenameField(
            model_name='salidaintercorp',
            old_name='nro_venta',
            new_name='nro_ventas',
        ),
        migrations.RemoveField(
            model_name='salidaintercorp',
            name='creado_por',
        ),
        migrations.RemoveField(
            model_name='salidaintercorp',
            name='tipo_venta',
        ),
        migrations.AddField(
            model_name='salidaintercorp',
            name='by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='salidaintercorp',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 6, 22, 3, 53, 41, 765051, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salidaintercorp',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
