# Generated by Django 5.0 on 2026-06-24 03:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0027_alter_salidaintercorp_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteVentaLibre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('mes_anio', models.CharField(blank=True, max_length=50, null=True)),
                ('asesor', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_cliente', models.CharField(blank=True, max_length=100, null=True)),
                ('dni_ruc', models.CharField(blank=True, max_length=50, null=True)),
                ('comprobante', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre_razon_social', models.CharField(blank=True, max_length=255, null=True)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('categoria', models.CharField(blank=True, max_length=150, null=True)),
                ('almacen_sjl', models.BooleanField(default=False)),
                ('sku_almacen', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('producto', models.CharField(blank=True, max_length=255, null=True)),
                ('precio_u', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cant', models.IntegerField(default=1)),
                ('costo_envio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('p_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('a_cuenta', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('restante', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('costo_x_prod', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('und', models.IntegerField(default=1)),
                ('costo_x_prod_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('flete', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('saldo_x_envio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ganancia', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('rentabilidad', models.CharField(blank=True, max_length=50, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reportes_ventalibre', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte Venta Libre',
                'verbose_name_plural': 'Reportes Venta Libre',
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
