# Generated by Django 5.0 on 2026-06-25 03:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0028_reporteventalibre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteTiktok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('venta_verificada', models.BooleanField(default=False)),
                ('asesor', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('mes', models.CharField(blank=True, max_length=50, null=True)),
                ('comprobante', models.CharField(blank=True, max_length=100, null=True)),
                ('dni_ruc', models.CharField(blank=True, max_length=50, null=True)),
                ('nombre_razon_social', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('categoria', models.CharField(blank=True, max_length=150, null=True)),
                ('sku_almacen', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('metodo_pago', models.CharField(blank=True, max_length=100, null=True)),
                ('precio_live', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cant', models.IntegerField(default=1)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('a_cuenta', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('restante', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('producto', models.CharField(blank=True, max_length=255, null=True)),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cantidad', models.IntegerField(default=1)),
                ('p_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('c_envio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('flete', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('costo_producto', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ganancia', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ganancia_con_envio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('rentabilidad', models.CharField(blank=True, max_length=50, null=True)),
                ('delivery_a_cargo', models.CharField(blank=True, max_length=150, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reportes_tiktok', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte Tiktok',
                'verbose_name_plural': 'Reportes Tiktok',
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
