# Generated by Django 5.0 on 2026-07-24 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0029_reportetiktok'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='activo_inventario_ssj2',
            field=models.BooleanField(default=False, verbose_name='Inventario SSJ 2'),
        ),
    ]
