# Generated by Django 5.0 on 2026-07-25 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0031_salidabci'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresopercheron',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Ubicación'),
        ),
    ]
