# Generated by Django 5.0 on 2026-07-26 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0033_salidaweb'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialEliminacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('plataforma_origen', models.CharField(blank=True, max_length=50, null=True)),
                ('usuario_que_elimino', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_eliminacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
