# Generated by Django 5.0 on 2026-07-26 20:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0034_historialeliminacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequerimientoAlerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_mes', models.CharField(blank=True, max_length=7, null=True, verbose_name='AÑO - MES')),
                ('fecha_solicitud', models.DateField(default=django.utils.timezone.now, verbose_name='FECHA DE SOLICITUD')),
                ('solicitado_por', models.CharField(blank=True, max_length=50, null=True, verbose_name='SOLICITADO POR')),
                ('cantidad', models.IntegerField(default=1, verbose_name='CANT.')),
                ('producto_solicitado', models.TextField(blank=True, null=True, verbose_name='NOMBRE Y MODELO DEL PRODUCTO')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='OBSERVACIONES')),
                ('plataforma_concepto', models.CharField(blank=True, max_length=100, null=True, verbose_name='PLATAFORMA / CONCEPTO')),
                ('fecha_entrega', models.DateField(blank=True, null=True, verbose_name='FECHA DE ENTREGA')),
                ('comentarios_compras', models.TextField(blank=True, null=True, verbose_name='COMENTARIOS DEL ÁREA DE COMPRAS')),
                ('compra_realizada', models.BooleanField(default=False, verbose_name='COMPRA REALIZADA (✓)')),
                ('agotado', models.BooleanField(default=False, verbose_name='AGOTADO (✓)')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'requerimientos_alertas',
                'ordering': ['-id'],
            },
        ),
    ]
