# Generated by Django 5.0 on 2026-07-28 19:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0035_requerimientoalerta'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportePaginaWeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reporte', models.DateField(default=django.utils.timezone.now, verbose_name='FECHA DE REPORTE')),
                ('asesor', models.CharField(blank=True, max_length=50, null=True, verbose_name='ASESOR QUE REPORTA OBS.')),
                ('tipo_observacion', models.CharField(blank=True, max_length=100, null=True, verbose_name='TIPO DE OBSERVACIONES')),
                ('comentarios', models.TextField(blank=True, null=True, verbose_name='COMENTARIOS ADICIONALES')),
                ('corregido', models.BooleanField(default=False, verbose_name='CORREGIDO POR EL RESPONSABLE')),
                ('marca', models.CharField(blank=True, max_length=50, null=True, verbose_name='MARCA')),
                ('categoria', models.CharField(blank=True, max_length=50, null=True, verbose_name='CATEGORÍA')),
                ('modelo', models.CharField(blank=True, max_length=100, null=True, verbose_name='MODELO')),
                ('producto', models.TextField(blank=True, null=True, verbose_name='PRODUCTO')),
                ('precio_tachado', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='P. TACHADO')),
                ('precio_web', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='P. WEB (+ 7%)')),
                ('precio_cyber', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='PRECIO CYBER Jared')),
                ('costo_producto', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='COSTO DEL PRODUCTO')),
                ('ganancia_cyber', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='GANANCIA CYBER Jared')),
                ('ganancia_web', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='GANANCIA P. WEB')),
                ('rentabilidad', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='RENTABILIDAD (%)')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'reportes_pagina_web',
                'ordering': ['-id'],
            },
        ),
    ]
