# Generated by Django 5.0 on 2026-07-28 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0037_evaluacionprecioweb_observacionweb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='observacionweb',
            name='link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='LINK'),
        ),
    ]
