# Generated by Django 5.0 on 2026-07-28 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0038_observacionweb_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='observacionweb',
            name='modelo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='MODELO'),
        ),
    ]
