# Generated by Django 5.0 on 2026-07-28 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0039_observacionweb_modelo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostoReferencial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(blank=True, max_length=100, null=True, verbose_name='MODELO')),
                ('producto', models.TextField(blank=True, null=True, verbose_name='PRODUCTO')),
                ('costo_cero_soles', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='COSTO CERO (S/.)')),
                ('costo_u_dolares', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='COSTO U. ($)')),
                ('costo_u_convertido', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='COSTO U. ($ ▶ S/.)')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'costos_referenciales',
                'ordering': ['-id'],
            },
        ),
    ]
